package_name: c
version: 0.10.0
license: GPLv2+
authors:
  - Jonathan Wakely <jwakely@redhat.com>
  - Petr Hracek <phracek@redhat.com>
  - Bohuslav Kabrda <bkabrda@redhat.com>
homepage: https://github.com/devassistant/dap-c
summary: C assistants
bugreports: https://github.com/devassistant/dap-c/issues
dependencies:
  - common_args
  - eclipse
  - git
  - github
  - vim
description: |
    Kickstarts new C project and more C related assistants
